Add hello microverse
Blessman-Newton/Microverse_Hello pull request #1
Opened 2023-07-04 10:05 UTC by Blessman-Newton

**Tasks: Hello Microverse**

_**I have ensured that:**_

1. There are no linter errors in the project.
2. Used Correct git-flow.
3.  Included a descriptive Readme file.
4. Used descriptive commit messages.
5. Followed the recommended HTML and CSS.
6. Documented my work in a professional manner according to Professional code
7.  Add node_modules to gitignore file.

2023-07-04 16:46 UTC, OyePriscilla requested changes
Hi @Blessman-Newton 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
GitHub flow observed ✔️
Ignonored `node_modules` and `test.md` files as required ✔️
Added `index.html` and `style.css` files ✔️
Linters checks passed ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 16:46 UTC, OyePriscilla commented on README.md
> +
- [ ]  Please ensure that your `live demo link` rediects visitors to the appropraite page, if you don't have a live demo link at the moment kindly remove the header.

2023-07-04 16:46 UTC, OyePriscilla commented on README.md
> +- **[key_feature_3]**
- [ ] The response in your key features are not engaging enough, kindly think of the key features (e.g. Add html file, set-up linters ....) you can add to your project. 👍

2023-07-04 16:46 UTC, OyePriscilla commented on README.md
> +
- [ ] The response in your  feature features headers are not engaging enough, kindly think of the feature features (e.g. Implement nav items, add images ...) you can add to your project. 👍

2023-07-04 16:46 UTC, OyePriscilla commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] For your README file to be more professional, kindly remove this placeholder. It's there to eplain how you can add a license file. 👍

2023-07-05 00:57 UTC, topeogunleye approved these changes
### Hi @Blessman-Newton, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Customized Key Features Section. ✔️ 
- Customized Future Features Section. ✔️ 
- Removed placeholder content for MIT license ✔️ 
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 01:01 UTC, merged